### ISSUE TITLE
[Bug] F2 Hide UI Fix hides other UI elements

### ISSUE THREAD

**Issue by HughesMDflyer4** [Bit-Studios/CommunityFixes#21]
If the HUD is hidden when in flight/map view prior to going to the VAB, main menu, or space center, most of or all of the UI elements will also be hidden, sometimes with no way to restore them other than restarting the game.

I'm not a Unity expert, but in my mod, I got the UI.FlightHud gameObject and called SetActive() on it. As far as I can tell this works, but I'm not sure if this is the safest/most graceful way, or if there are any other side effects.

**Comment by jan-bures** [comment]
Thanks for pointing that out! Fix is on the way

**Comment by jan-bures** [comment]
Fixed in #22
