### ISSUE TITLE
Make F2 work in Map3DView

### ISSUE THREAD

**Issue by schlosrat** [Bit-Studios/CommunityFixes#25]
**What will the fix solve? Please describe.**
Presently, when a player is in Map3DView and wants to take a pretty screenshot of the glorious orbit they've constructed, pressing F2 does not hide the UI, leaving the scene cluttered and less pretty

**Describe the solution you'd like**
Pressing F2 while in Map3DView should work as it does in FlightView and hide the stinking UI as it ought to! Put that guy back to work... We need to wake up F2 in Map View! No more long coffee breaks and nap time for you, Mr. F2!

**Additional context**
The current behavior is stock, and kinda lame if you ask me...

**Comment by jan-bures** [comment]
Fixed in #26
