### ISSUE TITLE
[New Fix] Missing R&D info for tech with multiple prerequisites

### ISSUE THREAD

**Issue by ghost** [Bit-Studios/CommunityFixes#42]
**What will the fix solve? Please describe.**
In R&D, when clicking on a technology with multiple prerequisites, feedback is only given for a single prerequisite in the left info panel

**Describe the solution you'd like**
A list of all prerequisites

**Additional context**
Just wondering if this is the kind of thing that's in scope for this project, if so I can investigate further if nobody else is already

**Comment by NathanPeake** [comment]
It has been decided that this fix will be added to the tech tree manager mod. 

https://spacedock.info/mod/3527/Tech%20Tree%20Manager
